'use client'
// import type { Metadata } from 'next'
// import '../styles/global.css'
// import { Provider } from 'react-redux/es/exports'
// import { store } from '@/store/store'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}) {
  return (
  //  <Provider store={store}>
     <html lang="en">
      <body>{children}</body>
    </html>
  //  </Provider>
  )
}
